# Generated by Django 2.1 on 2018-08-23 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('phno', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'CONTACT',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockname', models.CharField(max_length=20)),
                ('stockimg', models.CharField(max_length=20)),
                ('stockdes', models.CharField(max_length=500)),
                ('stockprice', models.IntegerField()),
            ],
            options={
                'db_table': 'STOCK',
            },
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('qpassword', models.CharField(max_length=20)),
                ('bal', models.IntegerField()),
            ],
            options={
                'db_table': 'USERDATA',
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='stockusername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockoverflow.Userdata'),
        ),
    ]
