# Generated by Django 2.1 on 2018-08-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockoverflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stockusername',
            field=models.CharField(max_length=20),
        ),
    ]
