# Generated by Django 2.1 on 2018-08-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockoverflow', '0002_auto_20180823_1907'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.AddField(
            model_name='userdata',
            name='stockname',
            field=models.CharField(default=12, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='stockprice',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
